### ISSUE TITLE
How to avoid CORS policy error?

### ISSUE THREAD

**Issue by evanre** [JanGolle/monobank-api-client#1]
Hey, I'm pretty new to JS async programming, can you help me with avoiding error: 

> Access to XMLHttpRequest at 'https://api.monobank.ua/personal/client-info' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Thanks

**Comment by jangolle** [comment]
Hi!)

Actually, it's look like you trying to use monobank-api-client module direct in your front application that made requests from browser and here we get some CORS issues. It's not about JS programming. It's about CORS itself. Your browser trying to made OPTIONS preflight request and server (api.monobank.ua) didn't respond with CORS headers that directly allow your origin (localhost) make this request. So your browser blocks that "unsafe" requests.

Short info about [CORS](https://www.codecademy.com/articles/what-is-cors)

And [here some "tips&tricks"](https://stackoverflow.com/a/35588856/6241332) how to avoid (mute) them in your browser if you just try to test API.

Hope it is all clear now.

You are welcome!
